# Generated by Django 3.1.4 on 2021-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='goal',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
    ]
