# Generated by Django 3.1.4 on 2021-02-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210201_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='record',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='record',
            name='duration',
        ),
    ]
