# Generated by Django 3.1.4 on 2021-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_record_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
