# Generated by Django 3.1.4 on 2021-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210201_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
