# Generated by Django 3.1.4 on 2021-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_record_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
