# Generated by Django 3.1.4 on 2021-02-01 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210201_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
